image: maven:3.8.4-openjdk-17

stages:
  - build
  - test
  

build_job:
  stage: build
  script:
    - echo "Building the project..."

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - mvn test
